name: 'PageSpeed Insights'
description: 'Action that wraps a call to the PageSpeed Insights API and returns the data'
author: 'wicksipedia'
inputs:
  url:
    description: "The URL to run the check against"
    required: true
  key:
    description: "A PageSpeed Insights API key"
    required: true
  categories:
    description: "Categories of checks to run (accessibility, best_practices, performance, pwa, seo)."
    required: false
    default: performance
  strategy:
    description: "Strategy to use when analyzing the page (mobile/desktop)."
    required: false
    default: mobile
  maximumNumberOfRetries:
    description: Maximum number of times to call API before failing the action
    required: false
    default: 3
  delayBetweenRetries:
    description: Duration in ms to wait before retrying
    required: false
    default: 3000
outputs:
  accessibility:
    description: accessibility output
  best_practices:
    description: best_practices output
  performance:
    description: performance output
  pwa:
    description: pwa output
  seo:
    description: seo output
runs:
  using: 'node16'
  main: 'dist/index.js'
